#!/usr/bin/env python3
"""Generate a Markdown VAL-05 incident report from anomaly score CSV output."""

from __future__ import annotations

import argparse
import csv
import os
from collections import Counter
from datetime import datetime
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create a VAL-05 incident report from anomaly scores.")
    parser.add_argument("--input", required=True, help="Path to anomaly_scores_<timestamp>.csv")
    parser.add_argument("--output-dir", help="Optional report output directory")
    return parser.parse_args()


def ts_to_iso(value: str) -> str:
    try:
        return datetime.fromtimestamp(float(value)).isoformat(timespec="milliseconds")
    except Exception:
        return value


def main() -> None:
    args = parse_args()
    if not os.path.exists(args.input):
        raise FileNotFoundError(f"Input not found: {args.input}")

    with open(args.input, "r", newline="", encoding="utf-8", errors="ignore") as f:
        rows = list(csv.DictReader(f))

    rows.sort(key=lambda r: float(r.get("timestamp", "0") or 0))
    severity_counts = Counter(r.get("severity", "UNKNOWN") for r in rows)
    rule_counts = Counter(r.get("rule_id", "UNKNOWN") for r in rows)

    if args.output_dir:
        out_dir = Path(args.output_dir)
    else:
        out_dir = Path(args.input).resolve().parents[1] / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"val05_incident_report_{int(datetime.now().timestamp())}.md"

    stop_recommended = any(
        r.get("severity") == "HIGH" or "STOP" in r.get("recommended_response", "").upper()
        for r in rows
    )

    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Sentinel-CPS VAL-05 Offline Incident Report\n\n")
        f.write(f"**Generated:** {datetime.now().isoformat(timespec='seconds')}\n\n")
        f.write(f"**Input anomaly score file:** `{os.path.abspath(args.input)}`\n\n")

        f.write("## Thesis-safe interpretation\n\n")
        f.write(
            "This report is generated by an offline, explainable anomaly-scoring MVP. "
            "It supports VAL-05 threat-detection and mitigation preparation, but it does not represent live automated mitigation. "
            "Any STOP action remains an operator-controlled or separately validated Gateway behavior until live integration is implemented and tested.\n\n"
        )

        f.write("## Executive summary\n\n")
        f.write(f"- Total anomaly rows: **{len(rows)}**\n")
        f.write(f"- HIGH severity: **{severity_counts.get('HIGH', 0)}**\n")
        f.write(f"- MEDIUM severity: **{severity_counts.get('MEDIUM', 0)}**\n")
        f.write(f"- LOW severity: **{severity_counts.get('LOW', 0)}**\n")
        f.write(f"- STOP recommended by offline analysis: **{'YES' if stop_recommended else 'NO'}**\n\n")

        if stop_recommended:
            f.write(
                "**Recommended response:** keep the system in STOP/LOCKED state during review, "
                "inspect Gateway actions, telemetry, and eBPF traces, and resume physical testing only after the cause is understood.\n\n"
            )
        else:
            f.write("**Recommended response:** continue observation and preserve logs for review.\n\n")

        f.write("## Triggered rules\n\n")
        if not rule_counts:
            f.write("No rules were triggered.\n\n")
        else:
            for rule, count in sorted(rule_counts.items()):
                f.write(f"- **{rule}:** {count} row(s)\n")
            f.write("\n")

        f.write("## Timeline of suspicious events\n\n")
        if not rows:
            f.write("No suspicious events were recorded.\n")
        else:
            for r in rows:
                f.write(
                    f"- **{ts_to_iso(r.get('timestamp', ''))}** "
                    f"`[{r.get('severity', '')}]` `{r.get('rule_id', '')}` "
                    f"{r.get('event_type', '')}: {r.get('description', '')} "
                    f"(response: {r.get('recommended_response', '')}; evidence: {r.get('evidence_reference', '')})\n"
                )

        f.write("\n## Inputs and evidence handling\n\n")
        f.write("- Preserve raw logs and reports in private OneDrive evidence storage.\n")
        f.write("- Public GitHub examples should use synthetic or redacted evidence only.\n")

    print(f"[*] Report generated at: {out_path}")


if __name__ == "__main__":
    main()
